### ISSUE TITLE
Didn't see anti-aliasing filter

### ISSUE THREAD

**Issue by happyTonakai** [cpuimage/resampler#4]
Did you perform an anti-aliasing filter when resampling?

**Comment by MarkusNoll** [comment]
Well you can check for the condition if output-sample-rate is lower than input-sample-rate. Then you can apply a low-cut filter before you start the resampling-process with fcut = f_out/2.

**Comment by happyTonakai** [comment]
OK so I have to apply the filter before resampler, right?

**Comment by MarkusNoll** [comment]
Exactly
